experiment: breast_cancer_mlp
  

dataset:
  loader: 
    name: numpy
    params: {"path":data/data.npz}
  name: breast_cancer
  preprocessing:
    split:
      train: 0.8
      val: 0.1
      test: 0.1
    shuffle: true
    normalize: true

model:
  type: sequential
  input_dim: 30
  architecture:
    - [batchnorm, 30]
    - [30, 64, relu]
    - [batchnorm, 64]
    - [64, 32, relu]
    - [Dropout, 0.2]
    - [32, 1, sigmoid]

training:
  batch_size: 16
  epochs: 50
  metric: accuracy
  optimizer:
    name: adam
    lr: 0.001
